### PR TITLE
feat: pass through json serialization options

### LINKED ISSUE #21: Easily print task or other model
Models are not easily printable. as_dict and as_json methods exist, but don't dump an indented/pretty form that's readable.

### PR DESCRIPTION
**Pull request by uniqueg**
Pass through arbitrary keyword arguments to `json.dumps()` in the [`Base.as_json()`](https://github.com/ohsu-comp-bio/py-tes/blob/a9ac2959fdb38bd31433d358724e20c2c544c6a1/tes/models.py#L97-L101) method.

Among other things, this can be used to "pretty print" a model (see #21), like so:

```python
import tes

task = tes.Task(
    executors=[
        tes.Executor(
            image="alpine",
            command=["echo", "hello"]
        )
    ]
)

print(task.as_json(indent=3))
```

Output:

```console
{
   "executors": [
      {
         "image": "alpine",
         "command": [
            "echo",
            "hello"
         ]
      }
   ]
}
```

Resolves #21

### CODE REVIEW

**Comment by kellrott** [comment]
I think this is producing a new unit test error. But I don't see how it's connected to the PR. Is it because the test is running in python 3.10 and a new error occurred?

**Comment by uniqueg** [comment]
Yes, looks like. I could try to fix this, but it will be hard to make this work for the wide range of versions specified in `setup.py` (`2.7`, `3.4`, `3.5` and `3.6`) and including `3.7` through to `3.10`.

Actually, all of the currently supported versions have been deprecated/unsupported for more than a year:
image

Personally, I think that whoever uses `py-tes` and was happy with it up until now (not many people asking for updates, features etc.) can likely go on using `py-tes` up to `0.4.2`, and I think we can safely break backwards compatibility from at least `3.5` and backwards (better `3.6`).

I could:
- Update dependency ranges to satisfy recent Python `3.7` through `3.10` patch versions
- Update the code, where necessary
- Update the GH Actions workflow to run tests with all these versions

What do you think @kellrott?

**Comment by kellrott** [comment]
It's probably worth the time to get it back in sync with the current Python release. And you are right, if someone needs an older version of Python, the 0.4.2 release of py-tes seems to have worked find so far.

**Comment by uniqueg** [comment]
Cool, I'll do that then.

**Comment by uniqueg** [comment]
Added to #44. Closing this PR

**Pull request closed without merging**
