### PR TITLE
Updated attr to remove deprecated convert argument

### PR DESCRIPTION
**Pull request by medcelerate**
The latest version of attrs had an issue with the convert argument, I switched it to convert.

### CODE REVIEW

**Comment by adamstruck** [comment]
Thanks for the contribution! I have a couple of requests before I merge this PR:

- make sure all file pass flake8 checks (this is why the travis builds are failing)
- update the minimum attrs version in [requirements.txt](https://github.com/ohsu-comp-bio/py-tes/blob/master/requirements.txt#L1) and [setup.py](https://github.com/ohsu-comp-bio/py-tes/blob/master/setup.py#L42)

**Comment by medcelerate** [comment]
Went ahead and made the fix. the attrs version is ok as the fix was a deprecated function option.

**Comment by adamstruck** [comment]
From what I saw in attrs [changelog](http://www.attrs.org/en/19.2.0/changelog.html): the change from `convert` => `converter` occurred in v17.4.0 and was removed completely in v19.2.0.  So I think that the minimum attrs version needs to be v.17.4.0.

**Comment by medcelerate** [comment]
Ok I will do so

**Comment by medcelerate** [comment]
Did you close the PR as it disappeared on my end?

**Comment by adamstruck** [comment]
Thanks!

**Pull request merged**
