### PR TITLE
Towards v0.5.0

### LINKED ISSUE #21: Easily print task or other model
Models are not easily printable. as_dict and as_json methods exist, but don't dump an indented/pretty form that's readable.

### LINKED ISSUE #42: Need different test runner
Nose is unmaintained and stopped working with Python 3.10:
https://github.com/minio/minio-py/issues/942

### LINKED ISSUE #43: Support newer Python versions
Support Python versions 3.7+ and drop support for 2.7, 3.4, 3.5 & 3.6.
See discussion [here](https://github.com/ohsu-comp-bio/py-tes/pull/41#issuecomment-1423315418).

### PR DESCRIPTION
**Pull request by uniqueg**
* Add support for Python `3.7`, `3.8`, `3.9`, `3.10` and `3.11`
* Drop support for Python `2.7`, `3.4`, `3.5` and `3.6`
* Update core and test dependencies
* Source core dependencies in `setup.py` from `requirements.txt`
* Run CI tests for all supported Python versions, in parallel
* Add type hints to all function and method signatures and critical local variables
* Fix some minor bugs
* Replace Nose test runner with Pytest
* Remove Travis CI configuration
* Remove `.coverage` artifacts
* Add typical Python patterns to `.gitignore` (from https://gitignore.io/)
* Pass through keyword args to `json.dumps()` in [`tes.models.Base.as_json()`](https://github.com/ohsu-comp-bio/py-tes/blob/a9ac2959fdb38bd31433d358724e20c2c544c6a1/tes/models.py#L97-L101); e.g., for pretty printing (see example in #41)
* Add advanced usage examples to docs

Resolves #42
Resolves #43 
Resolves #21

### CODE REVIEW

**Comment by uniqueg** [comment]
@kellrott: mind giving me write permisions to the repo?

**Comment by kellrott** [comment]
LGTM

**Comment by uniqueg** [comment]
Not sure what this last test is, and why it isn't run? Is this still some artifact from Travis CI?

**Comment by uniqueg** [comment]
@kellrott: I've cleaned up the branch, added some advanced usage examples to the doc, and changed the target to a release branch for `0.5.0`. Please check out one more time and merge if you think it's fine.

I'll add future features/fixes as individual PRs against the release branch.

**Pull request merged**
