### PR TITLE
Release 1.1.0 :tada:

### PR DESCRIPTION
**Pull request by lbeckman314**
Includes all updates made to the release-1.1.0 branch, including support for TES v1.1

### CODE REVIEW

**Comment by uniqueg** [comment]
Awesome, Liam :rocket:

I'm curious (but too lazy/busy to dive into the code): Is `py-tes` 1.1.0 backwards-compatible with TES 1.0.0 servers? And is there are general policy how client/server compatibility will be handled for `py-tes` (e.g. extra code, different branches, only maintaining support for latest server version)? Might be good to include some info on this in the docs.

**Comment by lbeckman314** [comment]
Hi Alex! Apologies for the astronomically late reply — backwards-compatibility with TES 1.1.0 servers is definitely something that we should ensure prior to this release, with steps for handling different versions being added to the documentation like you recommend.

Whether that support is from extra code or handled different branches is still a question to be answered.

Having the version support be on different branches is perhaps the quickest/easiest way in the short term, with maybe a long-term goal of having this be configurable both on the command line and within the `tes` module (manually by the user or automatically by querying the server).

I've just created [a new issue for this (#60)](https://github.com/ohsu-comp-bio/py-tes/issues/60) to track the progress on this. Please add any thoughts or suggestions on this compatibility support and we'll go from there! 🚀

**Comment by vsmalladi** [comment]
@lbeckman314  is this released yet?

**Comment by lbeckman314** [comment]
@vsmalladi Yes! Apologies for the delay — updating the GitHub release and docs today and will update here when complete 🙏

**Pull request merged**
